name: "Github action for deploy Vue app to Amazon s3 bucket 🗑"
description: "Easy way to build and upload distributibles files of Vue application to amazon s3 bucket"

branding:
  icon: "archive"
  color: "orange"

inputs:
  AWS_ACCESS_KEY_ID:
    description: "Amazon access key id"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "Amazon secret access key"
    required: true
  AWS_DEFAULT_REGION:
    description: "Bucket region. (Ex: us-east-1)"
    required: true
  AWS_BUCKET_NAME:
    description: "Aws bucket name"
    required: true
  PRIVATE_KEY:
    description: ""
    required: true
  APP_NAME:
    description: ""
    required: true
  USER_NAME:
    description: ""
    required: true
  HOST_NAME:
    description: ""
    required: true
  DEPLOY_COMMAND:
    description: "Command used to build your application. Ex: `npm run build`"  
    required: false
    default: production

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
    AWS_BUCKET_NAME: ${{ inputs.AWS_BUCKET_NAME }}
    PRIVATE_KEY: ${{ inputs.PRIVATE_KEY }}
    APP_NAME: ${{ inputs.APP_NAME}}
    USER_NAME: ${{ inputs.USER_NAME }}
    HOST_NAME: ${{ inputs.HOST_NAME }}
    DEPLOY_COMMAND: ${{ inputs.DEPLOY_COMMAND }}
